services:
  mongo:
    image: mongo:5.0
    restart: "no"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  drink_api:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      args:
        APP_VERSION: test
        BUILD_SHA: local
    restart: "no"
    environment:
      PORT: ${PORT:-5001}
      MONGO_URI: ${MONGO_URI:-mongodb://mongo:27017/drink}
      NODE_ENV: test
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - ./.env.test
    command: npm test -- --coverage