version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  drink_api_home_lab:
    container_name: drink_api_home_lab
    build:
      context: .
      dockerfile: src/Dockerfile
    image: ghcr.io/alepes-8/drink_api_home_lab:${GITHUB_SHA} # The image name to be used when pushing to GHCR
    ports:
      - "${PORT:-5001}:${PORT:-5001}"
    environment:
      - PORT=${PORT:-5001}
      - MONGO_URI=${MONGO_URI:-dummy}
      - JWT_SECRET=${JWT_SECRET:-dummy}
    depends_on:
      - mongo
          
volumes:
  mongo-data: